CHAMPION_NAMES = {
    "TFT17_Aatrox": "Aatrox",
    "TFT17_Akali": "Akali",
    "TFT17_Belveth": "Belveth",
    "TFT17_Blitzcrank": "Blitzcrank",
    "TFT17_Caitlyn": "Caitlyn",
    "TFT17_Chogath": "Chogath",
    "TFT17_Corki": "Corki",
    "TFT17_Ezreal": "Ezreal",
    "TFT17_Fiora": "Fiora",
    "TFT17_Gnar": "Gnar",
    "TFT17_Gragas": "Gragas",
    "TFT17_Graves": "Graves",
    "TFT17_Illaoi": "Illaoi",
    "TFT17_IvernMinion": "Ivern Minion",
    "TFT17_Jax": "Jax",
    "TFT17_Jhin": "Jhin",
    "TFT17_Kaisa": "Kaisa",
    "TFT17_Karma": "Karma",
    "TFT17_Kindred": "Kindred",
    "TFT17_Leblanc": "Leblanc",
    "TFT17_Leona": "Leona",
    "TFT17_Lissandra": "Lissandra",
    "TFT17_Maokai": "Maokai",
    "TFT17_MasterYi": "Master Yi",
    "TFT17_Milio": "Milio",
    "TFT17_Mordekaiser": "Mordekaiser",
    "TFT17_Morgana": "Morgana",
    "TFT17_Nasus": "Nasus",
    "TFT17_Nunu": "Nunu",
    "TFT17_Pantheon": "Pantheon",
    "TFT17_Rammus": "Rammus",
    "TFT17_Riven": "Riven",
    "TFT17_Sona": "Sona",
    "TFT17_Summon": "Summon",
    "TFT17_TahmKench": "Tahm Kench",
    "TFT17_Talon": "Talon",
    "TFT17_Teemo": "Teemo",
    "TFT17_TwistedFate": "Twisted Fate",
    "TFT17_Vex": "Vex",
    "TFT17_Zoe": "Zoe",
}

TRAIT_NAMES = {
    "TFT17_ADMIN": "Admin",
    "TFT17_APTrait": "Ap Trait",
    "TFT17_ASTrait": "As Trait",
    "TFT17_AnimaSquad": "Anima Squad",
    "TFT17_AssassinTrait": "Assassin Trait",
    "TFT17_Astronaut": "Astronaut",
    "TFT17_BlitzcrankUniqueTrait": "Blitzcrank Unique Trait",
    "TFT17_DRX": "Drx",
    "TFT17_DarkStar": "Dark Star",
    "TFT17_Fateweaver": "Fateweaver",
    "TFT17_FioraUniqueTrait": "Fiora Unique Trait",
    "TFT17_FlexTrait": "Flex Trait",
    "TFT17_GravesTrait": "Graves Trait",
    "TFT17_HPTank": "Hp Tank",
    "TFT17_JhinUniqueTrait": "Jhin Unique Trait",
    "TFT17_ManaTrait": "Mana Trait",
    "TFT17_MeleeTrait": "Melee Trait",
    "TFT17_MorganaUniqueTrait": "Morgana Unique Trait",
    "TFT17_Primordian": "Primordian",
    "TFT17_PsyOps": "Psy Ops",
    "TFT17_RangedTrait": "Ranged Trait",
    "TFT17_ResistTank": "Resist Tank",
    "TFT17_ShieldTank": "Shield Tank",
    "TFT17_SonaUniqueTrait": "Sona Unique Trait",
    "TFT17_SpaceGroove": "Space Groove",
    "TFT17_Stargazer_Mountain": "Stargazer Mountain",
    "TFT17_SummonTrait": "Summon Trait",
    "TFT17_TahmKenchUniqueTrait": "Tahm Kench Unique Trait",
    "TFT17_Timebreaker": "Timebreaker",
    "TFT17_VexUniqueTrait": "Vex Unique Trait",
}

ITEM_NAMES = {
    "TFT17_Item_Artifact_EvelynnArtifact": "Artifact Evelynn Artifact",
    "TFT17_Item_DarkStarEmblemItem": "Dark Star Emblem Item",
    "TFT17_Item_PsyOps_ChemicalCapacitorMod": "Psy Ops Chemical Capacitor Mod",
    "TFT17_Item_PulsefireEmblemItem": "Pulsefire Emblem Item",
    "TFT17_Item_ResistTankEmblemItem": "Resist Tank Emblem Item",
    "TFT17_Item_StargazerEmblemItem": "Stargazer Emblem Item",
    "TFT5_Item_StatikkShivRadiant": "Statikk Shiv Radiant",
    "TFT9_Item_CrownOfDemacia": "Crown Of Demacia",
    "TFT_Item_AdaptiveHelm": "Adaptive Helm",
    "TFT_Item_ArchangelsStaff": "Archangels Staff",
    "TFT_Item_Artifact_LightshieldCrest": "Artifact Lightshield Crest",
    "TFT_Item_BlueBuff": "Blue Buff",
    "TFT_Item_BrambleVest": "Bramble Vest",
    "TFT_Item_Crownguard": "Crownguard",
    "TFT_Item_Deathblade": "Deathblade",
    "TFT_Item_EmptyBag": "Empty Bag",
    "TFT_Item_GargoyleStoneplate": "Gargoyle Stoneplate",
    "TFT_Item_GuinsoosRageblade": "Guinsoos Rageblade",
    "TFT_Item_HextechGunblade": "Hextech Gunblade",
    "TFT_Item_InfinityEdge": "Infinity Edge",
    "TFT_Item_IonicSpark": "Ionic Spark",
    "TFT_Item_JeweledGauntlet": "Jeweled Gauntlet",
    "TFT_Item_LastWhisper": "Last Whisper",
    "TFT_Item_Leviathan": "Leviathan",
    "TFT_Item_MadredsBloodrazor": "Madreds Bloodrazor",
    "TFT_Item_Morellonomicon": "Morellonomicon",
    "TFT_Item_NeedlesslyLargeRod": "Needlessly Large Rod",
    "TFT_Item_PowerGauntlet": "Power Gauntlet",
    "TFT_Item_Quicksilver": "Quicksilver",
    "TFT_Item_RabadonsDeathcap": "Rabadons Deathcap",
    "TFT_Item_RapidFireCannon": "Rapid Fire Cannon",
    "TFT_Item_RecurveBow": "Recurve Bow",
    "TFT_Item_RedBuff": "Red Buff",
    "TFT_Item_Redemption": "Redemption",
    "TFT_Item_RunaansHurricane": "Runaans Hurricane",
    "TFT_Item_SpearOfShojin": "Spear Of Shojin",
    "TFT_Item_SpectralGauntlet": "Spectral Gauntlet",
    "TFT_Item_StatikkShiv": "Statikk Shiv",
    "TFT_Item_SteraksGage": "Steraks Gage",
    "TFT_Item_ThiefsGloves": "Thiefs Gloves",
    "TFT_Item_TitansResolve": "Titans Resolve",
    "TFT_Item_UnstableConcoction": "Unstable Concoction",
    "TFT_Item_WarmogsArmor": "Warmogs Armor",
}

AUGMENT_NAMES = {}
